[build-system]
requires = ["setuptools ~= 58.0"]

[project]
name = "frames"
description = "async dearpygui made easy"
authors = "Kim Timothy Engh"
version = "0.1.0"
dependencies = ["dearpygui>=1.8"]
requires-python = ">=3.8"
